### PR TITLE
Mention required packages to run (also install) from source

### PR DESCRIPTION
**Pull request by allentiak**
Hi, I've just cloned the repository, but I get no information regarding which libraries to install to make the program 
work (neither  tag "v1.0.2" nor "master").

Even though I can see it needs Python 3 and PyQT5.Qt.Quick (because it crashes otherwise), I don't know which packages to install (e.g., in Debian "testing", there are at least two packages related with Qt.Quick in Python3, `python3-pyqt5.qtquick` and `qml-module-qtquick2`. The one Pireal needs is the second one.).

### CODE REVIEW

**Comment by centaurialpha** [comment]
Thanks! but there is a problem to merge the branch

**Comment by centaurialpha** [comment]
I think the problem is because you not have the updated branch.

**Comment by allentiak** [comment]
I'll check it and get back to you.

**Comment by centaurialpha** [comment]
Good :)

**Comment by centaurialpha** [comment]
Anyway I have already included its changes and is on the list of contributors. Thanks!

**Comment by allentiak** [comment]
You're welcome.

**Pull request closed without merging**
